# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: mysql2
  socket: /tmp/mysql.sock
  #port: 5432
  encoding: utf8
  pool: 5 #<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: codigoin_michael
  password: 5uquThNX9QgS
  host: codigointerno.com.br
  database: codigoin_autenticador-google

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
